### ISSUE TITLE
New Pipeline System

### ISSUE THREAD

**Issue by Yey007** [Matamata-Animator/Matamata#27]
In order to clean up the mess I kind of made in #26 , I would like to propose an entirely new pipeline system for processing requests. My basic idea includes having a `Pipeline` class which stores a bunch of `PipelineSection` objects which each have a `run` method that takes some input and gives some output, whether those be text or video or whatever. Each sort of "section" we have right now (such as transcription, emotion detection, etc.) would be an implementation `PipelineSection`.

Let me know what you think.

**Comment by AI-Spawn** [comment]
Yeah, this sounds pretty cool. This would prob be a large undertaking, but it would also probably be good for long term support of this project. Do you want to be added as an assignee to this issue?

**Comment by Yey007** [comment]
I might do this at some point but not in the near future so feel free to close this is you think it's appropriate

**Comment by Yey007** [comment]
Alright I'm gonna close this as I know I'm not gonna do it (and it's not a good solution anyways)
